name: Test with jest

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: npm ci
      - name: Run nearley
        run: npm run nearley
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run start